### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'global'

### ISSUE THREAD

**Issue by navicore** [hologram-io/hologram-python#8]
when I `hologram activate --apikey 1234....` I get `ValueError: invalid literal for int() with base 10: 'global'` since the zone is 'global'

https://github.com/hologram-io/hologram-python/blob/ceb64bef03ed306b8090aa0f953cd44d4e03ad02/scripts/hologram_activate.py#L149

**Comment by lellasone** [comment]
I have also run into this issue.

**Comment by rbalik** [comment]
This is fixed in v0.8.1. Thanks for reporting.
