### ISSUE TITLE
install fails missing python-sdk-auth

### ISSUE THREAD

**Issue by jqtruong** [hologram-io/hologram-python#9]
If you run into SDK issues, please go [here](https://community.hologram.io/c/hardware/sdk) for help and support:

You should open a GitHub issue only if it is a bug or a feature request.

------------------------

### Describe the problem
The install fails with a missing package: *python-sdk-auth*.

### Expected behavior
Not fail. not ever.

### Actual behavior
```bash
Searching for python-sdk-auth==0.2.1
Reading https://pypi.org/simple/python-sdk-auth/
No local packages or working download links found for python-sdk-auth==0.2.1
error: Could not find suitable distribution for Requirement.parse('python-sdk-auth==0.2.1')
make: *** [Makefile:4: install] Error 1
```

### Steps to reproduce the behavior
either `make install` from this repo, or executing the install script: http://hologram.io/python-install.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux raspberrypi 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux
- **Python SDK installed via PyPI or GitHub**: n/a, tried with `pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)` and `make install` from this repo
- **SDK version (use command below)**: n/a, trying to install [0.8.0](https://github.com/hologram-io/hologram-python/blob/master/version.txt)
- **Python version**: Python 2.7.13
- **Hardware (modem) model**: Raspberry Pi 3 B+

**Comment by rbalik** [comment]
The package exists on pypi: https://pypi.org/project/python-sdk-auth/

Maybe they're having an issue right now? Was your Pi connected to the internet via ethernet or wifi when you ran the installer?

**Comment by rbalik** [comment]
Hi, is this still an issue for you?

**Comment by rbalik** [comment]
We're going to close this because it seems like it was just a transient pypi issue.
